---
- name: Deploy Docker Config
  copy:
    content: "{{ docker_daemon_options | default() | to_nice_json }}"
    dest: /etc/docker/daemon.json
  when: docker_daemon_options is defined
  notify:
    - Restart Docker
  become: true

- name: Start Docker Service
  service:
    name: "{{ docker_service_name }}"
    state: started
  become: true
